/**
 * Trefle API v1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.6.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.vhjv0i.planty.model

/**
 * 
 * @param id 
 * @param commonName 
 * @param slug 
 * @param scientificName 
 * @param year 
 * @param bibliography 
 * @param author 
 * @param familyCommonName 
 * @param genusId 
 * @param mainSpeciesId 
 * @param vegetable 
 * @param observations 
 * @param mainSpecies 
 * @param sources 
 * @param links 
 */

import com.google.gson.annotations.SerializedName

data class Plant (
        @SerializedName("id")
        val id: kotlin.Int,
        @SerializedName("common_name")
        val commonName: kotlin.String? = null,
        @SerializedName("slug")
        val slug: kotlin.String,
        @SerializedName("scientific_name")
        val scientificName: kotlin.String,
        @SerializedName("image_url")
        val imageUrl: kotlin.String,
        @SerializedName("year")
        val year: kotlin.Int? = null,
        @SerializedName("bibliography")
        val bibliography: kotlin.String? = null,
        @SerializedName("author")
        val author: kotlin.String? = null,
        @SerializedName("family_common_name")
        val familyCommonName: kotlin.String? = null,
        @SerializedName("genus_id")
        val genusId: kotlin.Int? = null,
        @SerializedName("main_species_id")
        val mainSpeciesId: kotlin.Int? = null,
        @SerializedName("vegetable")
        val vegetable: kotlin.Boolean? = null,
        @SerializedName("observations")
        val observations: kotlin.String? = null
) {
}