/**
 * Trefle API v1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.6.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.vhjv0i.planty.model

/**
 * 
 * @param id 
 * @param commonName 
 * @param slug 
 * @param scientificName 
 * @param year 
 * @param bibliography 
 * @param author 
 * @param familyCommonName 
 * @param genusId 
 * @param mainSpeciesId 
 * @param vegetable 
 * @param observations 
 * @param mainSpecies 
 * @param sources 
 * @param links 
 */

import com.google.gson.annotations.SerializedName

data class PlantBase (
        @SerializedName("data")
        val data: Plant,
) {
}