/**
 * Trefle API v1
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.6.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

/**
 * 
 * @param id 
 * @param commonName 
 * @param slug 
 * @param scientificName 
 * @param year 
 * @param bibliography 
 * @param author 
 * @param familyCommonName 
 * @param genusId 
 * @param mainSpeciesId 
 * @param vegetable 
 * @param observations 
 * @param mainSpecies 
 * @param sources 
 * @param links 
 */
data class Plant (

    val id: kotlin.Int,
    val commonName: kotlin.String? = null,
    val slug: kotlin.String,
    val scientificName: kotlin.String,
    val year: kotlin.Int? = null,
    val bibliography: kotlin.String? = null,
    val author: kotlin.String? = null,
    val familyCommonName: kotlin.String? = null,
    val genusId: kotlin.Int? = null,
    val mainSpeciesId: kotlin.Int? = null,
    val vegetable: kotlin.Boolean? = null,
    val observations: kotlin.String? = null
) {
}